### PR TITLE
feat: add scheduler support for fluentbit collector

### PR DESCRIPTION
**Pull request by ksdpmx**
### What this PR does / why we need it:

allow customers to specify custom scheduler for fluentbit collector as requested from [this comment](https://github.com/fluent/fluent-operator/pull/771#issuecomment-1574624390). along with minor typo fix.

### Which issue(s) this PR fixes:

Fixes #

### Does this PR introduced a user-facing change?

```release-note
allow customers to specify custom scheduler for fluentbit collector
```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by ksdpmx** [comment]
> 2023-06-06T03:10:30Z    ERROR   Reconciler error        {"controller": "collector", "controllerGroup": "fluentbit.fluent.io", "controllerKind": "Collector", "Collector": {"name":"fluent-bit-collector","namespace":"fluent"}, "namespace": "fluent", "name": "fluent-bit-collector", "reconcileID": "b0128934-0ce5-4a21-9105-aa7df920cddd", "error": "error when handling finalizer: resource name may not be empty"}

btw i don't really agree with [this review](https://github.com/fluent/fluent-operator/pull/484#discussion_r1050314832).

**Comment by benjaminhuo** [comment]
> > 2023-06-06T03:10:30Z    ERROR   Reconciler error        {"controller": "collector", "controllerGroup": "fluentbit.fluent.io", "controllerKind": "Collector", "Collector": {"name":"fluent-bit-collector","namespace":"fluent"}, "namespace": "fluent", "name": "fluent-bit-collector", "reconcileID": "b0128934-0ce5-4a21-9105-aa7df920cddd", "error": "error when handling finalizer: resource name may not be empty"}
> 
> btw i don't really agree with [this review](https://github.com/fluent/fluent-operator/pull/484#discussion_r1050314832).
> 
> > delete it directly.
> 
> resources haven't been generated before calling `Delete()` which leads to the remaining finalizer for collector.
> 
> > Why does not delete the clusterrole and clusterrolebinding?
> 
> for [this review](https://github.com/fluent/fluent-operator/pull/484#discussion_r1050314610), does it make sense to add an owner reference in the managed clusterrole and clusterrolebinding for gc controller, given this controller is not supposed to have permission to delete clusterrole/clusterrolebinding?

@wanjunlei @wenchajun would you take a look at @ksdpmx‘s opinion?

**Review by benjaminhuo — APPROVED** [review]

**Comment by benjaminhuo** [comment]
> > 2023-06-06T03:10:30Z    ERROR   Reconciler error        {"controller": "collector", "controllerGroup": "fluentbit.fluent.io", "controllerKind": "Collector", "Collector": {"name":"fluent-bit-collector","namespace":"fluent"}, "namespace": "fluent", "name": "fluent-bit-collector", "reconcileID": "b0128934-0ce5-4a21-9105-aa7df920cddd", "error": "error when handling finalizer: resource name may not be empty"}
> 
> btw i don't really agree with [this review](https://github.com/fluent/fluent-operator/pull/484#discussion_r1050314832).
> 
> > delete it directly.
> 
> resources haven't been generated before calling `Delete()` which leads to the remaining finalizer for collector.
> 
> > Why does not delete the clusterrole and clusterrolebinding?
> 
> for [this review](https://github.com/fluent/fluent-operator/pull/484#discussion_r1050314610), does it make sense to add an owner reference in the managed clusterrole and clusterrolebinding for gc controller, given this controller is not supposed to have permission to delete clusterrole/clusterrolebinding?

You're welcome to create a PR to fix whatever you think it's a problem and @wanjunlei @wenchajun will review that

**Comment by ksdpmx** [comment]
> does it make sense to add an owner reference in the managed clusterrole and clusterrolebinding for gc controller, given this controller is not supposed to have permission to delete clusterrole/clusterrolebinding?

fluentbit collector is a namespace-scoped resource which cannot own other cluster-scoped resource.

**Comment by benjaminhuo** [comment]
@ksdpmx have added you as fluent operator maintainer, thanks for your contribution! @wanjunlei @wenchajun @patrick-stephens

**Pull request merged**
