### PR TITLE
fix: added Collector CRD to kustomization & Helm ClusterRole template

### LINKED ISSUE #513: bug: missing "collector" resource from the cluster role fluentbit.fluent.io API group
### Describe the issue

Deploying the fluent-operator with fluent-bit option enabled with `--set Kubernetes=true,containerRuntime=containerd` throws the below error in the fluent-operator logs and fails to run fluentbit resource.

```
failed to list *v1alpha2.Collector: collectors.fluentbit.fluent.io is forbidden: User "system:serviceaccount:fluent:fluent-operator" cannot list resource "collectors" in API group "fluentbit.fluent.io" at the cluster scop
```

### To Reproduce

`helm upgrade fluent-operator --create-namespace -n fluent charts/fluent-operator/  --set Kubernetes=true,containerRuntime=containerd`

### Expected behavior

Upon deployment of the operator, fluentbit daemon set should start running, however, no daemon set and pod are present. 

### Your Environment

```markdown
- Fluent Operator version: 1.7.1
- Container Runtime: containerd
```

### How did you install fluent operator?

Via helm command provided in the README.md.

### Additional context

Workaround for me was upon deployment of the operator to go into the `fluent` cluster role and add `collectors` into the list of resources within the `fluentbit.fluent.io` API group.

I wasn't sure where to add the changes to the code of the operator, hence the bug issue.

Thanks in advance!

Marjan

### PR DESCRIPTION
**Pull request by jjsiv**
### Which issue(s) this PR fixes:

I guess this was missed as a part of #484 - currently 'make manifests' does not generate the Collector CRD in manifests/setup because kustomization is missing it.
Also Fixes #513 - added Collector to the ClusterRole Helm template

### Does this PR introduced a user-facing change?

```release-note
No
```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by wenchajun — APPROVED** [review]

**Comment by benjaminhuo** [comment]
@wenchajun you'll need to merge the changes in https://github.com/fluent/helm-charts/pull/299 to this repo, and then this PR needs to be rebased on the latest helm charts changes

**Comment by benjaminhuo** [comment]
@jjsiv Would you help to rebase your PR and resolve the conflicts?

**Comment by jjsiv** [comment]
Looks like the test went through ok but it failed on cleanup for some reason...

**Review by benjaminhuo — APPROVED** [review]

**Comment by benjaminhuo** [comment]
> Looks like the test went through ok but it failed on cleanup for some reason...

I've made some changes to the CI script and now the CI work
Thanks for the PR @jjsiv

**Pull request merged**
