### PR TITLE
update README to mention new namespace FluentBit CRDs

### PR DESCRIPTION
**Pull request by adiforluls**
### Which issue(s) this PR fixes:

Fixes #

### Does this PR introduced a user-facing change?

```release-note

```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by adiforluls** [comment]
I'm thinking if https://github.com/kubesphere-sigs/fluent-operator-walkthrough should move to fluent-operator repository as a sub-directory. Feels like a remnant that's residing in another workspace.

**Comment by benjaminhuo** [comment]
> I'm thinking if https://github.com/kubesphere-sigs/fluent-operator-walkthrough should move to fluent-operator repository as a sub-directory. Feels like a remnant that's residing in another workspace.

Good suggestion, we'll considering moving it!

**Review by benjaminhuo — APPROVED** [review]

**Comment by benjaminhuo** [comment]
@adiforluls Thanks for updating the docs

I'm not sure if you can also help to adjust https://github.com/fluent/fluent-operator/blob/master/docs/images/fluent-operator.svg too.

The image is created using draw.io and the original .drawio file is here:
https://github.com/fluent/fluent-operator/blob/master/docs/images/fluent-operator.drawio

**Comment by adiforluls** [comment]
Sure I can look into it.

**Pull request merged**
