### PR TITLE
feat: Add CI templates for fluent-operator

### LINKED ISSUE #207: Add CI templates  for fluentbit-operator
Refer to https://github.com/fluent/fluentd/tree/master/.github

/help
/first-good-issue

### PR DESCRIPTION
**Pull request by mangoGoForward**
Signed-off-by: mango <xu.weiKyrie@foxmail.com>

### What this PR does / why we need it:
Add CI templates for fluentbit-operator.

### Which issue(s) this PR fixes:

Fixes #207

### Does this PR introduced a user-facing change?

```release-note
None
```

### Additional documentation, usage docs, etc.:

```docs
- [Other doc]: https://github.com/fluent/fluent-operator/pull/242
```

### CODE REVIEW

**Comment by mangoGoForward** [comment]
please have a look. @zhu733756

**Review by zhu733756 — APPROVED** [review]

**Comment by zhu733756** [comment]
> please have a look. @zhu733756

Thanks for the great contribution!

**Comment by mangoGoForward** [comment]
Seems those yaml file's end need a blank line, and I forgot to add.

**Comment by zhu733756** [comment]
> Seems those yaml file's end need a blank line, and I forgot to add.

No matter, you can implement it by git forced pushing.

**Comment by mangoGoForward** [comment]
> > Seems those yaml file's end need a blank line, and I forgot to add.
> 
> No matter, you can implement it by git forced pushing.

Done.

**Review by benjaminhuo — APPROVED** [review]

**Comment by benjaminhuo** [comment]
@mangoGoForward This is a great supplement to the current workflow, thanks for the contribution!
And thanks @zhu733756 's review

**Pull request merged**
