### PR TITLE
update fluentbit to 3.1.7

### PR DESCRIPTION
**Pull request by jiuxia211**
### Which issue(s) this PR fixes:

Fixes #

### Does this PR introduced a user-facing change?

```release-note
update fluentbit to 3.1.7
```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by benjaminhuo** [comment]
3.1.7 is out yesterday

**Comment by jiuxia211** [comment]
> 3.1.7 is out yesterday

Already updated

**Review by wenchajun — APPROVED** [review]

**Review by benjaminhuo — APPROVED** [review]

**Comment by Cajga** [comment]
@jiuxia211 @benjaminhuo @wenchajun ,
The image does not seems to be available in the fluent-operator repo. I receive the following error:
```
  Warning  Failed     21s (x3 over 64s)  kubelet            Failed to pull image "ghcr.io/fluent/fluent-operator/fluent-bit:3.1.7": rpc error: code = NotFound desc = failed to pull and unpack image "ghcr.io/fluent/fluent-operator/fluent-bit:3.1.7": failed to resolve reference "ghcr.io/fluent/fluent-operator/fluent-bit:3.1.7": ghcr.io/fluent/fluent-operator/fluent-bit:3.1.7: not found
```

Also with podman/docker:
```
$ podman pull ghcr.io/fluent/fluent-operator/fluent-bit:3.1.7
Trying to pull ghcr.io/fluent/fluent-operator/fluent-bit:3.1.7...
Error: initializing source docker://ghcr.io/fluent/fluent-operator/fluent-bit:3.1.7: reading manifest 3.1.7 in ghcr.io/fluent/fluent-operator/fluent-bit: manifest unknown
```

The available tags are:
```
$  skopeo list-tags docker://ghcr.io/fluent/fluent-operator/fluent-bit
{
    "Repository": "ghcr.io/fluent/fluent-operator/fluent-bit",
    "Tags": [
        "master",
        "latest",
        "master-debug",
        "latest-debug",
        "pr-1034",
        "pr-1034-debug",
        "pr-1055",
        "pr-1055-debug",
        "pr-1117",
        "pr-1117-debug",
        "pr-1123",
        "pr-1123-debug",
        "pr-1153",
        "pr-1153-debug",
        "pr-1177",
        "pr-1177-debug",
        "pr-1181",
        "pr-1181-debug",
        "pr-1186",
        "pr-1186-debug",
        "3.0.4",
        "v3.0.4",
        "3.0.4-debug",
        "v3.0.4-debug",
        "3.0-debug",
        "3.0",
        "v3.0-debug",
        "v3.0",
        "3.0.7",
        "v3.0.7",
        "3.0.7-debug",
        "v3.0.7-debug",
        "3.1.0",
        "v3.1.0",
        "3.1",
        "v3.1",
        "3.1.0-debug",
        "v3.1.0-debug",
        "3.1-debug",
        "v3.1-debug",
        "3.1.2",
        "v3.1.2",
        "3.1.2-debug",
        "v3.1.2-debug",
        "3.1.3",
        "v3.1.3",
        "3.1.3-debug",
        "v3.1.3-debug",
        "3.1.4",
        "v3.1.4",
        "3.1.4-debug",
        "v3.1.4-debug",
        "3.1.4-1",
        "v3.1.4-1",
        "3.1.4-1-debug",
        "v3.1.4-1-debug",
        "3.1.5",
        "v3.1.5",
        "3.1.5-debug",
        "v3.1.5-debug"
    ]
}

```

**Comment by benjaminhuo** [comment]
> The image does not seems to be available in the fluent-operator repo. I receive the following error:

I triggered the build action just now:

https://github.com/fluent/fluent-operator/actions/runs/10846695407

**Pull request merged**
