### PR TITLE
release 3.2.0

### PR DESCRIPTION
**Pull request by cw-Guo**
### What this PR does / why we need it:
release 3.2.0
### Which issue(s) this PR fixes:

Fixes #

### Does this PR introduced a user-facing change?

```release-note

```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cw-Guo** [comment]
@benjaminhuo i followed the document and also the previous release PRs to create this PR. 
Reference:
- https://github.com/fluent/fluent-operator/pull/1202
- https://github.com/fluent/fluent-operator/pull/1203

I will create the next PR once you review and merge this one. 

Just to confirm, the target branch release-3.2 should be created directly via the UI right?

**Comment by cw-Guo** [comment]
@benjaminhuo by the way, we may need some automation to automate this process, and also introduce some naming requirements over the PR titles (so that the automation will be easier).

**Review by wenchajun — APPROVED** [review]

**Review by wenchajun — APPROVED** [review]

**Comment by wenchajun** [comment]
I pulled a new branch, https://github.com/fluent/fluent-operator/tree/release-3.2
Are you interested in continuing to finish the rest of the work today?
If not, I will finish these remaining jobs.

**Comment by wenchajun** [comment]
like this https://github.com/fluent/fluent-operator/tree/release-3.1

**Comment by joshuabaird** [comment]
@cw-Guo @wenchajun @benjaminhuo How do we handle Helm chart versioning?  Should the helm chart version track the fluent-operator version?  I see the latest helm chart version is v3.1.0 while v3.2.0 of the fluent-operator has been released.

**Comment by benjaminhuo** [comment]
T

> @cw-Guo @wenchajun @benjaminhuo How do we handle Helm chart versioning? Should the helm chart version track the fluent-operator version? I see the latest helm chart version is v3.1.0 while v3.2.0 of the fluent-operator has been released.
> 
> If not, should [appVersion](https://github.com/fluent/fluent-operator/blob/bc8a7562b90dd3664970291886dea20be39b5a3b/charts/fluent-operator/Chart.yaml#L23) be v3.2.0?

The chart's version and appversion should be updated whenever a release is out.
@wenchajun would you help to revise the dev guide ?

**Pull request merged**
