### PR TITLE
tests: add utils related unit tests

### PR DESCRIPTION
**Pull request by mangoGoForward**
Signed-off-by: mango <xu.weiKyrie@foxmail.com>

### What this PR does / why we need it:
Add utils related unit tests

### Which issue(s) this PR fixes:

Resolved part of #220 

### Does this PR introduced a user-facing change?

```release-note
None
```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by mangoGoForward** [comment]
please have a look @benjaminhuo

**Comment by zhu733756** [comment]
Thanks for the contributions, The issue means that we need more functional test cases and e2e tests for the Fluent Bit api, not the pkg, :)

**Comment by zhu733756** [comment]
Ref: https://github.com/fluent/fluent-operator/blob/master/apis/fluentbit/v1alpha2/clusterfluentbitconfig_types_test.go

Could you add more tests like here?    :)

**Comment by mangoGoForward** [comment]
> Ref: https://github.com/fluent/fluent-operator/blob/master/apis/fluentbit/v1alpha2/clusterfluentbitconfig_types_test.go
> 
> Could you add more tests like here? :)

Yes, I want to commit more pr to resolve this issue #220.

**Comment by zhu733756** [comment]
> > Ref: https://github.com/fluent/fluent-operator/blob/master/apis/fluentbit/v1alpha2/clusterfluentbitconfig_types_test.go
> > Could you add more tests like here? :)
> 
> Yes, I want to commit more pr to resolve this issue #220.

Good idea. You can make it in this pr with other commits.

**Comment by mangoGoForward** [comment]
Hi @zhu733756 , I have added some test files about input and output types, please have a review if you have free time.

**Comment by zhu733756** [comment]
> Hi @zhu733756 , I have added some test files about input and output types, please have a review if you have free time.

Good job! I will see it later!

**Comment by mangoGoForward** [comment]
> Good job! I will see it later!

This project's open source protocol is APL 2.0, but there are many files which License header missing, may we can add some commands like `update-license` and `verify-license` with [skywalking-eyes](https://github.com/apache/skywalking-eyes)

**Comment by zhu733756** [comment]
Yes. Seems good to me.

**Review by benjaminhuo — APPROVED** [review]

**Comment by benjaminhuo** [comment]
@mangoGoForward Thanks for the contribution!

**Pull request merged**
