### PR TITLE
Update fluentbit to v3.0.7

### PR DESCRIPTION
**Pull request by joshuabaird**
### What this PR does / why we need it:

Updates to 3.0.7 for patches/security updates.

### Which issue(s) this PR fixes:
N/A

### CODE REVIEW

**Review by benjaminhuo — APPROVED** [review]

**Comment by benjaminhuo** [comment]
we're changing the image registry from dockerhub to ghcr in this PR @wanjunlei @wenchajun @Gentleelephant

**Comment by benjaminhuo** [comment]
@joshuabaird Thanks, don't forget to change the default fluentbit and fluentd tag for the workflow

**Comment by joshuabaird** [comment]
@benjaminhuo Looks like the image is actually being pushed as `ghcr.io/fluent/fluent-operator/fluent-bit` and not `ghcr.io/fluent/fluent-operator/fluentbit` (see the hyphen).  PR incoming to fix.

**Comment by joshuabaird** [comment]
@benjaminhuo fix for the missing hyphen:  https://github.com/fluent/fluent-operator/pull/1201

**Pull request merged**
