### PR TITLE
minor typo fix for firehose

### PR DESCRIPTION
**Pull request by ksdpmx**
### Which issue(s) this PR fixes:

Fixes #

### Does this PR introduced a user-facing change?

```release-note
None
```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by benjaminhuo** [comment]
@ksdpmx Thanks for the contribution, you'll need to sign your commit by:
```shell
git commit -s --amend
git push -f
```

**Comment by ksdpmx** [comment]
Thanks for reminding. This commit has been amended.

**Comment by benjaminhuo** [comment]
> Thanks for reminding. This commit has been amended.

The commit is still not signed 
image

**Comment by ksdpmx** [comment]
done.. it's caused by multiple email settings.

**Review by benjaminhuo — APPROVED** [review]

**Pull request merged**
