### PR TITLE
feat: add HostAliases support to Fluent Bit and Fluentd specifications

### PR DESCRIPTION
**Pull request by MioOgbeni**
### What this PR does / why we need it:

Hi, I need to have option to set HostAliases into FluentD and FluentBit pods, so I decided to add this option directly to the operator for everyone. :)

### Which issue(s) this PR fixes:

None

### Does this PR introduced a user-facing change?

```release-note
- HostAliases can be now passed into FluentD and FluentBit Pods.
```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jjsiv** [comment]
Can you  run  `make generate`?

**Review by jjsiv — COMMENTED** [review]
Can you run `make generate`?

**Comment by MioOgbeni** [comment]
Hey, no problem. Previously I edited the CRD and setup manifests manually, but now I also generated them via `make manifests`, so now they are correctly autogenerated. 


But when I do `make generate`, the only change is the removal of this constraints in all `zz_generated.deepcopy` files. Is this a required change? It doesn't relate to my changes, but to go version (I'm using `go1.22.9`)
https://github.com/fluent/fluent-operator/blob/e2f6c80339fccd44b13a78a916f511c7d728e165/apis/fluentbit/v1alpha2/plugins/custom/zz_generated.deepcopy.go#L2

**Comment by jjsiv** [comment]
Ok, that's good. The `make generate` should also update the generated DeepCopy function for FluentBit with the new HostAliases field
https://github.com/fluent/fluent-operator/blob/master/apis/fluentbit/v1alpha2/zz_generated.deepcopy.go#L955

**Review by benjaminhuo — APPROVED** [review]

**Pull request merged**
