### PR TITLE
Namespace level secret loader for namespaced FluentBit configs

### LINKED ISSUE #653: FluentBit: Check for secrets in the same namespace as the resources for namespaced custom resources
### Is your feature request related to a problem? Please describe.

Since we now have namespace CRDs and configs for FluentBit, defining a namespace where all the secrets used by the plugins will reside and be searched for will be a bad idea for namespaced configs, because then any malicious namespace tenant can reference that secret simply by name, which leads to privilege escalation. 

### Describe the solution you'd like

For cluster-level resources, keep using https://github.com/fluent/fluent-operator/blob/ec97502046d2d5077c9bcdd8d1f6279faee55ebf/apis/fluentbit/v1alpha2/clusterfluentbitconfig_types.go#L46

For namespace-level resources, look for secrets in the same namespace as the resources.

### Additional context

I'll fix this

### PR DESCRIPTION
**Pull request by adiforluls**
### What this PR does / why we need it:
For namespaced FluentBit configs, search for secrets in the same namespace as the configs.

### Which issue(s) this PR fixes:

Fixes #653 

### Does this PR introduced a user-facing change?

```release-note

```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by wenchajun — APPROVED** [review]

**Comment by adiforluls** [comment]
Thanks for the approval, but looks like the checks are hosed and have been waiting for about 3 hours. I can merge but would want a clean test run first. @benjaminhuo or @wenchajun can you help run the pipeline checks?

**Comment by adiforluls** [comment]
@wenchajun looks like these checks are hosed again, there might be a problem in the pipeline

**Comment by wenchajun** [comment]
> Thanks for the approval, but looks like the checks are hosed and have been waiting for about 3 hours. I can merge but would want a clean test run first. @benjaminhuo or @wenchajun can you help run the pipeline checks?
> 
> ```
> Requested labels: ubuntu-18.04
> Job defined at: fluent/fluent-operator/.github/workflows/main.yaml@refs/pull/674/merge
> Waiting for a runner to pick up this job...
> ```

It looks like it needs to be run in `ubuntu-18.04`, I'll fix it later.

**Review by benjaminhuo — APPROVED** [review]

**Comment by benjaminhuo** [comment]
@wenchajun would you please help to fix the CI error?

image

https://github.com/fluent/fluent-operator/actions/runs/4624664163/jobs/8179715069

**Comment by wenchajun** [comment]
> @wenchajun would you please help to fix the CI error which is related to the changes in this PR?
> 
> image
> 
> https://github.com/fluent/fluent-operator/actions/runs/4624664163/jobs/8179715069

Ok， I will fix it

**Pull request merged**
