### PR TITLE
Fix release cycles for fluentd and fluentbit images manually.

### LINKED ISSUE #1178: bug: tags missing from images in docker hub
### Describe the issue

Latest chart uses fluent bit image tag v3.0.4 but that image tag is not on docker hub.

### To Reproduce

try and pull image from docker hub.

Step 2/2 : FROM kubesphere/fluent-bit:${IMAGE_VERSION}
12:19:23     manifest for kubesphere/fluent-bit:v3.0.4 not found: manifest unknown: manifest unknown

### Expected behavior

Image is available to support the chart

### Your Environment

```markdown
- Fluent Operator version: 2.8.0
- Container Runtime: containerd
- Operating system: Linux
- Kernel version:
```

### How did you install fluent operator?

Helm 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sarathchandra24**
### What this PR does / why we need it:
https://github.com/fluent/fluent-operator/issues/1178 
https://github.com/fluent/fluent-operator/pull/1079

1. Current Github workflows are following the same release cycle. 
2. We have three different images fluent-bit, fluent-operator and fluentd, but these are on different release cycle and following same tag doesn't apply. Also we don't want to fallback on the make files again. 
3. So instead of creating the images using tags, it asks for a input of what release number to follow and then docker image tags are build likewise. 

Links to workflow runs:
1. Fluent Operator released on tag: https://github.com/sarathchandra24/fluent-operator/actions/runs/9248567473
2. Fluent Operator released on master: https://github.com/sarathchandra24/fluent-operator/actions/runs/9248514441
3. Fluent Bit released manually by specifying tag as input for workflow: https://github.com/sarathchandra24/fluent-operator/actions/runs/9248457484
4. Fluentd released manually by specifying tag as input for workflow: https://github.com/sarathchandra24/fluent-operator/actions/runs/9248735165

How to trigger manually

image

### Which issue(s) this PR fixes:

Fixes #1178 

### Does this PR introduced a user-facing change?

```release-note

```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by benjaminhuo — APPROVED** [review]

**Comment by benjaminhuo** [comment]
That's terrific, thank you!

**Comment by sarathchandra24** [comment]
Fluentd image build successful for tag 1.15.3: https://github.com/fluent/fluent-operator/actions/runs/9262668827
Fluent Bit image build successful for tag 3.0.4: https://github.com/fluent/fluent-operator/actions/runs/9262666460

**Comment by sarathchandra24** [comment]
Yes as per semver thing it is expected, but I can remove it if required. So when ever we release a x.y.z it will also tag x.y to x.y.z. it is controlled over here https://github.com/fluent/fluent-operator/blob/master/.github/workflows/build-fb-image.yaml#L126-L129 and https://github.com/fluent/fluent-operator/blob/master/.github/workflows/build-fb-image.yaml#L65-L68. I think it's ok to have it, but if you want me to remove it I can raise a PR for it.

**Comment by benjaminhuo** [comment]
> I think it's ok to have it, but if you want me to remove it I can raise a PR for it.

it's ok to keep it, thank you!

**Pull request merged**
