### PR TITLE
feat(plugin): support fluentd loki output

### LINKED ISSUE #310: Add Loki output support for Fluentd
### Is your feature request related to a problem? Please describe.

Yes, since loki is easy and simple to ingest logs, it would be great if the loki plugin is available for fluentd

### Describe the solution you'd like

Loki output plugin should exist for fluend similar to fluent-bit

### Describe alternatives you've considered

None

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Fatpa**
### Which issue(s) this PR fixes:

Fixes #310 

### Does this PR introduced a user-facing change?

```release-note
None
```

### Additional documentation, usage docs, etc.:

```docs
apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterOutput
metadata:
  name: fluentd-output-loki
  labels:
    output.fluentd.fluent.io/enabled: "true"
spec: 
  outputs: 
  - loki:
      host: loki-logging-data.kubesphere-logging-system.svc
      port: 3100
```

### CODE REVIEW

**Comment by benjaminhuo** [comment]
@Fatpa Thanks for the contribution! 
Would you sign your commit as below?
```shell
git commit -s --amend
git push -f
```

Thanks!

**Comment by Fatpa** [comment]
> @Fatpa Thanks for the contribution! Would you sign your commit as below?
> 
> ```shell
> git commit -s --amend
> git push -f
> ```
> 
> Thanks!

Of course. Done.

**Comment by wenchajun** [comment]
As far as I know, the fluentd image doesn't have the loki plugin built in, so we should modify this dockerfile file.
https://github.com/fluent/fluent-operator/blob/master/cmd/fluent-watcher/fluentd/Dockerfile.amd64#L38

**Comment by wanjunlei** [comment]
Why add a new TLS plugin in `apis/fluentd/v1alpha1/plugins`, we should use the TLS plugin in `apis/fluentbit/v1alpha2/plugins`.

in addition, we should move the `TLS`, `ConfigMapLoader`, and `SecretLoader` to a new package to avoid duplicate definitions.

**Comment by Fatpa** [comment]
> Why add a new TLS plugin in `apis/fluentd/v1alpha1/plugins`, we should use the TLS plugin in `apis/fluentbit/v1alpha2/plugins`.
> 
> in addition, we should move the `TLS`, `ConfigMapLoader`, and `SecretLoader` to a new package to avoid duplicate definitions.

Just follow the current design for the apis/fluentd and avoid the differences between fluentd and fluentbit.
I also think the common package is the best to avoid duplicate definitions.

**Comment by Fatpa** [comment]
> As far as I know, the fluentd image doesn't have the loki plugin built in, so we should modify this dockerfile file. https://github.com/fluent/fluent-operator/blob/master/cmd/fluent-watcher/fluentd/Dockerfile.amd64#L38

I will add it.

**Comment by benjaminhuo** [comment]
> Why add a new TLS plugin in `apis/fluentd/v1alpha1/plugins`, we should use the TLS plugin in `apis/fluentbit/v1alpha2/plugins`.
> 
> in addition, we should move the `TLS`, `ConfigMapLoader`, and `SecretLoader` to a new package to avoid duplicate definitions.

@wenchajun You can create another PR to move tls to a common place

**Comment by benjaminhuo** [comment]
@Fatpa Thanks very much for the contribution!

**Review by benjaminhuo — APPROVED** [review]

**Comment by benjaminhuo** [comment]
@Fatpa Would you please create another PR to add docs to the Fluentd Loki plugin as https://github.com/fluent/fluent-operator/blob/master/docs/plugins/fluentd/index.md  ?

Thanks
Benjamin

**Comment by Fatpa** [comment]
> 

Sure. I will make it in a few days.

**Pull request merged**
