### PR TITLE
release-2.7.0

### PR DESCRIPTION
**Pull request by antrema**
### Which issue(s) this PR fixes:

Fixes #

### Does this PR introduced a user-facing change?

```release-note
release 2.7.0
```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by wenchajun — APPROVED** [review]

**Review by benjaminhuo — APPROVED** [review]

**Comment by wenchajun** [comment]
I see that there is no image for fluent-operatorv2.7, you should create a new tag `release-2.7` and post it here. https://github.com/fluent/fluent-operator/releases

**Comment by antrema** [comment]
> I see that there is no image for fluent-operatorv2.7, you should create a new tag `release-2.7` and post it here. https://github.com/fluent/fluent-operator/releases

@wenchajun I tried to create the tag "v2.7.0", but it seems that I don't have the right to do this, I will try through the release page

**Comment by wenchajun** [comment]
> > I see that there is no image for fluent-operatorv2.7, you should create a new tag `release-2.7` and post it here. https://github.com/fluent/fluent-operator/releases
> 
> @wenchajun I tried to create the tag "v2.7.0", but it seems that I don't have the right to do this, I will try through the release page

ok，I have pushed tag `v2.7.0`

**Comment by wenchajun** [comment]
see https://github.com/fluent/fluent-operator/tags

**Comment by antrema** [comment]
I published

**Comment by benjaminhuo** [comment]
@antrema would you help to sync the v2.7.0 chart https://github.com/fluent/fluent-operator/tree/v2.7.0/charts/fluent-operator to https://github.com/fluent/helm-charts/tree/main/charts/fluent-operator by a new PR?

**Comment by antrema** [comment]
> @antrema would you please help to sync the v2.7.0 chart https://github.com/fluent/fluent-operator/tree/v2.7.0/charts/fluent-operator to https://github.com/fluent/helm-charts/tree/main/charts/fluent-operator by a new PR and cc me and @wenchajun for review?

@benjaminhuo What are you expecting from me ? a full update (files trees are not the same) or only update of version and CRDs (keeping the file architecture) ?

**Comment by benjaminhuo** [comment]
> What are you expecting from me ? a full update (files trees are not the same) or only update of version and CRDs (keeping the file architecture) ?
Sorry for the confusion. Fluent Operator maintainers are responsible for syncing the latest Fluent Operator charts https://github.com/fluent/fluent-operator/tree/v2.7.0/charts/fluent-operator to fluent community's official repo https://github.com/fluent/helm-charts/tree/main/charts/fluent-operator.

It's out of sync for the last few releases. I think we can keep the file trees of https://github.com/fluent/fluent-operator/tree/v2.7.0/charts/fluent-operator which is the upstream.

**Pull request merged**
