### PR TITLE
Add gelf output plugin to fluentbit

### LINKED ISSUE #881: Add gelf output plugin for FluentBit
### Is your feature request related to a problem? Please describe.

The gelf output plugin is available in fluentbit: https://docs.fluentbit.io/manual/pipeline/outputs/gelf but not in the fluent-operator. 
The current solution is to use the customPlugin output to use gelf.

### Describe the solution you'd like

Add gelf output plugin for fluentbit in fluent-operator so that users could stop using customPlugin features to use gelf.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by alexandrevilain**
### Which issue(s) this PR fixes:

Fixes #881

### Does this PR introduced a user-facing change?

```release-note
Add gelf output plugin to fluentbit
```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by wenchajun — COMMENTED** [review]
Is the corresponding `match` field missing?

**Comment by alexandrevilain** [comment]
Hi @wenchajun ! Thanks for the review.

> Is the corresponding `match` field missing?

I don't think it's missing because it's handled by this part of the code: https://github.com/fluent/fluent-operator/blob/master/apis/fluentbit/v1alpha2/clusteroutput_types.go#L153 

If I create the following manifest:
```yaml
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: test
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/mode: "fluentbit-only"
spec:
  matchRegex: "*"
  gelf:
    host: 127.0.0.1
    port: 12202
    mode: tls
    tls:
      verify: true
```

The generated configuration looks like:
```console
[Output]
    Name    gelf
    Match_Regex    *
    Host    gra1.logs.ovh.com
    Port    12202
    Mode    tls
    tls    On
    tls.verify    true
```

Here it uses matchRegex but it's the same as for match.

But maybe I'm wrong ?

**Comment by benjaminhuo** [comment]
@patrick-stephens what do you think?

**Comment by patrick-stephens** [comment]
> @patrick-stephens @wanjunlei what do you think?

Not sure what you're querying here - all filter+output plugins support `match` and `match_regex`.
I think the docs have just included the field explicitly.

**Comment by benjaminhuo** [comment]
> > @patrick-stephens @wanjunlei what do you think?
> 
> Not sure what you're querying here - all filter+output plugins support `match` and `match_regex`. I think the docs have just included the field explicitly.

Agree, Match & MatchRegex are common attributes of output plugins:
https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/configuration-file#config_output
https://github.com/fluent/fluent-operator/blob/master/apis/fluentbit/v1alpha2/clusteroutput_types.go#L39

**Review by benjaminhuo — APPROVED** [review]

**Pull request merged**
